import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import icon from "../app/favicon.ico";
import Head from "next/head";
import { PokemonProvider, usePokemonContext } from "@/context/context";

const montserrat = Montserrat({ weight: ["700", "400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GiornomDex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonProvider>
        <body className={`${montserrat.className}`}>
          {children}
        </body>
      </PokemonProvider>
    </html>
  );
}
